apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps-app
spec:
  loadBalancerIP: 172.17.0.11
  ports:
  - port: 21
    protocol: TCP
    name: ftps
  - port: 21000
    protocol: TCP
    name: ftps-data
  selector:
    app: ftps-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  selector:
    matchLabels:
      app: ftps-app
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - name: ftps
        image: services/ftps
        imagePullPolicy: Never
        env:
        - name: FTP_USER
          value: admin
        - name: FTP_PASSWORD
          value: admin
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 21000
          hostPort: 21000
