apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana-app
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.8
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: services/grafana
        livenessProbe:
          exec:
            command:
            - telegraf
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
