apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    nodePort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: services/grafana
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        env:
          - name: FTP_USER
            value: gsharony
          - name: FTP_PASSWORD
            value: password
          - name: DB_NAME
            value: grafana
          - name: DB_USER
            value: wp_admin
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql-svc
