apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb-app
spec:
  ports:
  - port: 8086
  selector:
    app: influxdb-app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb
        image: services/influxdb
        ports:
        - containerPort: 8086
        imagePullPolicy: Never
