apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb-app
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.9
  ports:
  - port: 8086
    nodePort: 8086
    protocol: TCP
    name: http
  selector:
    app: influxdb-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb
        image: services/influxdb
        ports:
        - containerPort: 8086
        imagePullPolicy: Never
        env:
          - name: FTP_USER
            value: gsharony
          - name: FTP_PASSWORD
            value: password
          - name: DB_NAME
            value: nginx
          - name: DB_USER
            value: wp_admin
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql-svc
