apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-app
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    nodePort: 3306
    protocol: TCP
    name: http
  selector:
    app: mysql-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        image: services/mysql
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            value: mysql
          - name: DB_USER
            value: wp_admin
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql-svc
