apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.5
  ports:
  - port: 22
    protocol: TCP
    name: ssh
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: services/nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /root/script/liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        imagePullPolicy: Never
