apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: services/nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: Never
        env:
          - name: FTP_USER
            value: gsharony
          - name: FTP_PASSWORD
            value: password
          - name: DB_NAME
            value: nginx
          - name: DB_USER
            value: wp_admin
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql-svc
