apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress-app
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.7
  ports:
  - port: 5050
    protocol: TCP
    name: http
  selector:
    app: wordpress-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: services/wordpress
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - telegraf
          initialDelaySeconds: 5
          periodSeconds: 3
        imagePullPolicy: Never
        env:
          - name: DB_NAME
            value: wordpress
          - name: DB_USER
            value: admin
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql-svc
