FROM alpine:latest

RUN apk add --no-cache --upgrade bash mariadb mariadb-client mysql mysql-client openrc \
telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

COPY srcs/script /root/script
COPY srcs/config /root/config
COPY srcs/files /root/files

EXPOSE 3306

CMD /root/script/setup.sh
